[package]
edition = "2021"
name = "jam-crypto-napi"
version = "0.0.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
# Default enable napi4 feature, see https://nodejs.org/api/n-api.html#node-api-version-matrix
napi = { version = "2.16.9", default-features = false, features = ["napi4"] }
napi-derive = "2.16.9"
ark-vrf = { version = "0.1.1", features = ["bandersnatch", "ring"] }
hex = "0.4.3"
ed25519-zebra = { package = "ed25519-zebra", version = "4" }

[build-dependencies]
napi-build = "2.1.3"

[profile.release]
lto = true
strip = "symbols"
